# Generated by Django 4.2 on 2023-05-02 09:33

import Academy.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subcategory', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('info', tinymce.models.HTMLField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('story', tinymce.models.HTMLField()),
                ('country_of_origin', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler)),
                ('video', models.FileField(blank=True, null=True, upload_to=Academy.models.video_upload_handler)),
                ('category', models.ManyToManyField(to='Academy.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sorting', models.IntegerField(choices=[(1, 'Lighthouse'), (2, 'Regular')], verbose_name='Regular or Lighthouse product')),
                ('info', tinymce.models.HTMLField()),
                ('tasting_notes', tinymce.models.HTMLField()),
                ('abv', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Alcohol %')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler)),
                ('shop_link', models.URLField()),
                ('consumer_shop_link', models.URLField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.category')),
            ],
        ),
    ]
