# Generated by Django 4.2 on 2023-05-02 19:42

import Academy.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1000, 600], upload_to=Academy.models.image_upload_handler)),
            ],
        ),
    ]
