# Generated by Django 4.2 on 2023-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0005_alter_category_slug_alter_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
