# Generated by Django 4.2 on 2023-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0006_alter_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreimages',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
