# Generated by Django 4.2 on 2023-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0007_coreimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coreimages',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
