# Generated by Django 4.2 on 2023-05-12 06:40

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0008_alter_blog_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='image'),
        ),
    ]
