# Generated by Django 4.2 on 2023-05-14 14:47

import Academy.models
from django.db import migrations
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0009_alter_category_image_alter_category_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'subcategory']},
        ),
        migrations.AddField(
            model_name='category',
            name='teaser',
            field=tinymce.models.HTMLField(default='teaser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_footer_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 600], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=None, size=[1000, 600], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to='image'),
        ),
        migrations.AlterField(
            model_name='coreimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
    ]
