# Generated by Django 4.2 on 2023-05-14 14:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0010_alter_category_options_category_teaser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='none', force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[500, 500], upload_to='image'),
            preserve_default=False,
        ),
    ]
