# Generated by Django 4.2 on 2023-05-14 19:20

import Academy.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0011_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreimages',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[500, 500], upload_to=Academy.models.logo_upload_handler),
        ),
        migrations.AlterField(
            model_name='coreimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to='core_images'),
        ),
    ]
