# Generated by Django 4.2 on 2023-05-15 11:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0012_remove_coreimages_name_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='bottle',
            name='technical_info',
            field=tinymce.models.HTMLField(default='none'),
            preserve_default=False,
        ),
    ]
