# Generated by Django 4.2 on 2023-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0013_alter_bottle_options_bottle_technical_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sorting',
            field=models.IntegerField(choices=[(1, 'Lighthouse'), (2, 'Regular')], default=1, verbose_name='Regular or Lighthouse product'),
            preserve_default=False,
        ),
    ]
