# Generated by Django 4.2 on 2023-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0014_brand_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
