# Generated by Django 4.2 on 2023-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0015_alter_bottle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='website_link',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
