# Generated by Django 4.2 on 2023-05-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0017_bottle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='slug',
        ),
    ]
