# Generated by Django 4.2 on 2023-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0018_remove_bottle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
