# Generated by Django 4.2 on 2023-05-22 07:35

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0019_bottle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='technical_info',
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_agave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_aging',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_cooking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_distillation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_extraction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_fermentation',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_nom',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_other',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_still',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
