# Generated by Django 4.2 on 2023-05-22 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0020_remove_bottle_technical_info_bottle_tech_agave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='tech_agave',
            new_name='tech_aging_barrels',
        ),
        migrations.AddField(
            model_name='bottle',
            name='bottle_size',
            field=models.IntegerField(default=700, validators=[django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_batch_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_blend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_filtration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_mash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='tech_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
