# Generated by Django 4.2 on 2023-06-01 22:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0022_rename_tech_source_bottle_tech_source_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='sorting',
            field=models.IntegerField(choices=[(1, 'Lighthouse'), (2, 'Regular')], verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_aging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aging'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_aging_barrels',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Barrel(s)'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_batch_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Batch size'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_blend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blend'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_cooking',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cooking method'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_distillation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Distillation'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_extraction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extraction method'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_fermentation',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Fermentation info'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_filtration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filtration'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_mash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mash'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_nom',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='NOM'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_other',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_source_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source material'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_still',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Still type'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='tech_water_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Water source'),
        ),
    ]
