# Generated by Django 4.2 on 2023-06-12 21:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0024_bottle_tech_botanicals'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
