# Generated by Django 4.2 on 2023-06-15 15:21

import Academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0026_bottle_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=models.ImageField(upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
