# Generated by Django 4.2 on 2023-06-15 15:26

import Academy.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0027_alter_bottle_image_alter_bottle_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
    ]
