# Generated by Django 4.2 on 2023-06-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0028_alter_bottle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bottle',
            options={'ordering': ['sorting', 'category', 'name']},
        ),
    ]
