# Generated by Django 4.2 on 2023-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0029_agegate_alter_bottle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegate',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
