# Generated by Django 4.2 on 2023-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0030_alter_agegate_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bottle_tag',
            field=models.ManyToManyField(to='Academy.bottle'),
        ),
        migrations.AddField(
            model_name='blog',
            name='brand_tag',
            field=models.ManyToManyField(to='Academy.brand'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category_tag',
            field=models.ManyToManyField(to='Academy.category'),
        ),
    ]
