# Generated by Django 4.2 on 2023-06-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0031_blog_bottle_tag_blog_brand_tag_blog_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bottle_tag',
            field=models.ManyToManyField(blank=True, null=True, to='Academy.bottle'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='brand_tag',
            field=models.ManyToManyField(blank=True, null=True, to='Academy.brand'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_tag',
            field=models.ManyToManyField(blank=True, null=True, to='Academy.category'),
        ),
    ]
