# Generated by Django 4.2 on 2023-06-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0033_alter_blog_bottle_tag_alter_blog_brand_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_footer_image',
            new_name='footer_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_teaser',
            new_name='teaser',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_video',
            new_name='video',
        ),
    ]
