# Generated by Django 4.2 on 2024-01-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0034_rename_blog_footer_image_blog_footer_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_date_create']},
        ),
    ]
