# Generated by Django 4.2 on 2024-01-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0035_alter_blog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agegate',
            old_name='city',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='agegate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='agegate',
            name='region',
        ),
    ]
