# Generated by Django 4.2 on 2024-01-24 13:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0036_rename_city_agegate_ip_remove_agegate_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[200, 200], upload_to='thumbnails'),
        ),
    ]
