# Generated by Django 4.2 on 2024-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0037_alter_bottle_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
