# Generated by Django 4.2 on 2024-01-29 20:16

import Academy.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0038_alter_bottle_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[100, 600], upload_to=Academy.models.image_upload_handler)),
                ('related_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.blog')),
            ],
        ),
    ]
