# Generated by Django 4.2 on 2024-02-01 09:17

import Academy.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0039_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='footer_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=None, size=[1000, 600], upload_to=Academy.models.image_upload_handler),
        ),
    ]
