# Generated by Django 4.2 on 2024-04-05 08:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0041_remove_blogimage_name_alter_blogimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1000, 600], upload_to='blog'),
        ),
    ]
