# Generated by Django 4.2 on 2024-05-03 07:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0042_alter_blogimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='footer_image',
            new_name='hero_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=None, size=[1000, 600], upload_to='blog'),
        ),
    ]
