# Generated by Django 4.2 on 2024-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0045_blogimage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
