# Generated by Django 4.2 on 2024-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0046_alter_blogimage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='type_tag',
            field=models.ManyToManyField(blank=True, to='Academy.blogtype'),
        ),
    ]
