# Generated by Django 4.2 on 2024-05-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0047_blogtype_blog_type_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='text',
            new_name='image_text',
        ),
    ]
