# Generated by Django 4.2 on 2024-05-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0048_rename_text_blogimage_image_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='type_tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='type_tag',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Academy.blogtype'),
            preserve_default=False,
        ),
    ]
