# Generated by Django 4.2 on 2024-05-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0049_remove_blog_type_tag_blog_type_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academy.blogtype'),
        ),
    ]
