# Generated by Django 4.2 on 2024-05-17 08:07

import Academy.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0050_alter_blog_type_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hero_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1000, 600], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[1000, 600], upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to=Academy.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 500], upload_to=Academy.models.logo_upload_handler),
        ),
        migrations.AlterField(
            model_name='coreimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1000, 1000], upload_to='core_images'),
        ),
    ]
