# Generated by Django 4.2 on 2024-06-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0054_alter_bottle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='thumbnail',
        ),
    ]
