# Generated by Django 4.2 on 2024-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0055_remove_bottle_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'ordering': ['sorting', 'category', 'brand', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
