# Generated by Django 4.2 on 2024-06-18 19:36

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0056_alter_bottle_options_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1000, 600], upload_to='recipe')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'order', 'subcategory']},
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrelated_product', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Amount')),
                ('type', models.IntegerField(choices=[(1, 'Ml'), (2, 'Piece'), (3, 'Gram')], verbose_name='Sort order')),
                ('related_product', models.ManyToManyField(blank=True, null=True, to='Academy.bottle')),
                ('related_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.recipe')),
            ],
        ),
    ]
