# Generated by Django 4.2 on 2024-06-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0058_alter_recipeingredient_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='related_product',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academy.bottle'),
        ),
    ]
