# Generated by Django 4.2 on 2024-06-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0059_remove_recipeingredient_related_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
