# Generated by Django 4.2 on 2024-06-21 08:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0060_alter_bottle_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desciption',
            field=tinymce.models.HTMLField(default='x'),
            preserve_default=False,
        ),
    ]
