# Generated by Django 4.2 on 2024-06-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0061_recipe_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desciption',
            new_name='description',
        ),
    ]
