# Generated by Django 4.2 on 2024-06-21 13:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0063_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_steps',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='type',
            field=models.IntegerField(choices=[(1, 'ML'), (2, 'Piece'), (3, 'Gram')], verbose_name='Type'),
        ),
    ]
