# Generated by Django 4.2 on 2024-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0065_recipeingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='type',
            field=models.IntegerField(choices=[(1, 'ML'), (2, 'Piece'), (3, 'Gram'), (4, 'Dash')], verbose_name='Type'),
        ),
    ]
