# Generated by Django 4.2 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0066_alter_recipeingredient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sour'), (2, 'Martini'), (3, 'Old Fashioned'), (4, 'Highball'), (5, 'Punch')], default=1, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
