# Generated by Django 4.2 on 2024-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0067_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='occasion',
            field=models.IntegerField(choices=[(1, 'Aperitif'), (2, 'After Dinner'), (3, 'Night Out'), (4, ' Easy At Home'), (5, 'Festive')], default=1, verbose_name='Occasion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='taste',
            field=models.IntegerField(choices=[(1, 'Bitter'), (2, 'Sweet'), (3, 'Sour'), (4, 'Heavy'), (5, 'Light`')], default=1, verbose_name='Taste'),
            preserve_default=False,
        ),
    ]
