# Generated by Django 4.2 on 2024-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0069_bottle_tech_fruits_alter_bottle_tech_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='tech_mezcal_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mezcal type'),
        ),
    ]
