# Generated by Django 4.2 on 2024-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0070_bottle_tech_mezcal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('video_upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
