# Generated by Django 4.2 on 2024-08-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0070_bottle_tech_mezcal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_upload_date', models.DateTimeField(auto_created=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('related_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.blog')),
            ],
        ),
    ]
