# Generated by Django 4.2 on 2024-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0071_blogvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='categories'),
        ),
    ]
