# Generated by Django 4.2 on 2024-08-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0072_remove_blogvideo_video_url_blogvideo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogvideo',
            name='related_blog',
        ),
    ]
