# Generated by Django 4.2 on 2024-08-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0072_alter_category_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideo',
            name='related_blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Academy.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='file',
            field=models.URLField(),
        ),
    ]
