# Generated by Django 4.2 on 2024-08-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0073_remove_blogvideo_related_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogvideo',
            old_name='video',
            new_name='file',
        ),
    ]
