# Generated by Django 4.2 on 2024-08-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0073_blogvideo_related_blog_alter_blogvideo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=1024)),
            ],
        ),
    ]
