# Generated by Django 4.2 on 2024-08-14 21:14

import Academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0074_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='categories', validators=[Academy.models.validate_file_size]),
        ),
    ]
