# Generated by Django 4.2 on 2024-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0074_rename_video_blogvideo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogvideo',
            name='video_upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
