# Generated by Django 4.2 on 2024-08-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0075_alter_category_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='occasion',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='occasion',
            field=models.ManyToManyField(to='Academy.recipeoccasion', verbose_name='Occasion'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='taste',
            field=models.ManyToManyField(to='Academy.recipetaste', verbose_name='Taste'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.ManyToManyField(to='Academy.recipetype', verbose_name='Type'),
        ),
    ]
